---
# tasks file for ldomb.manage-ec2-instances
- name: Provision EC2 Box
  local_action:
    module: ec2
    key_name: "{{ ec2_keypair }}"
    group_id: "{{ ec2_security_group }}"
    instance_type: "{{ ec2_instance_type }}"
    image: "{{ ec2_image }}"
    vpc_subnet_id: "{{ ec2_subnet_ids|random }}"
    region: "{{ ec2_region }}"
    instance_tags: '{"Name":"{{ec2_tag_Name}}","Type":"{{ec2_tag_Type}}","Environment":"{{ec2_tag_Environment}}"}'
    assign_public_ip: yes
    wait: true
    count: 1
    volumes:
    - device_name: /dev/sda1
      device_type: gp2
      volume_size: "{{ ec2_volume_size }}"
      delete_on_termination: true
  register: ec2

- debug: var=item
  with_items: "{{ ec2.instances }}"

- add_host: name={{ item.public_ip }} >
         groups=tag_Type_{{ec2_tag_Type}},tag_Environment_{{ec2_tag_Environment}}
         ec2_tag_Name={{ec2_tag_Name}}
         ec2_region={{ec2_region}}
         ec2_tag_Type={{ec2_tag_Type}}
         ec2_tag_Environment={{ec2_tag_Environment}}
         ec2_ip_address={{item.public_ip}}
  with_items: "{{ ec2.instances }}"

- name: Wait for SSH banners
  local_action: wait_for port=22 host="{{ item.public_ip }}" search_regex=OpenSSH delay=5
  become: False
  with_items: "{{ ec2.instances }}"
